import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from langchain.tools import BaseTool
from typing import Optional

class EmailTool:
    """Tool for sending email recommendations to businesses."""
    
    def __init__(self):
        # Email configuration - these should be set as environment variables
        self.smtp_server = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.environ.get("SMTP_PORT", "587"))
        self.smtp_username = os.environ.get("SMTP_USERNAME", "bhaskar007777777@gmail.com")
        self.smtp_password = os.environ.get("SMTP_PASSWORD", "egpxqckfpezijprm")
        self.sender_email = os.environ.get("SENDER_EMAIL", "bhaskar007777777@gmail.com")
    
    def send_email(self, recipient_email: str, subject: str, message_body: str) -> str:
        """
        Send an email with the advertising recommendation.
        
        Args:
            recipient_email (str): The recipient's email address
            subject (str): Email subject
            message_body (str): The recommendation message
            
        Returns:
            str: Confirmation message or error
        """
        try:
            # Create a multipart message
            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = recipient_email
            msg['Subject'] = subject
            # Add HTML body with nice formatting
            # Convert newlines to HTML breaks outside f-string to avoid backslash issues
            html_message_body = message_body.replace('\n', '<br>')
            html_body = f"""
            <html>
                <head>
                    <style>
                        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
                        h1 {{ color: #0066cc; }}
                        .footer {{ margin-top: 30px; font-size: 12px; color: #999; }}
                    </style>
                </head>
                <body>
                    <div class="container">
                        <h1>Advertising Recommendation</h1>
                        {html_message_body}
                        <div class="footer">
                            <p>This recommendation was generated by the Advertising Advisor AI.</p>
                        </div>
                    </div>
                </body>
            </html>
            """
            
            msg.attach(MIMEText(html_body, 'html'))
            
            # Check if we have email credentials
            if not self.smtp_username or not self.smtp_password:
                return "Email sending skipped: No SMTP credentials provided in environment variables."
            
            # Connect to the SMTP server and send the email
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.smtp_username, self.smtp_password)
            server.send_message(msg)
            server.quit()
            
            return f"Email successfully sent to {recipient_email}"
            
        except Exception as e:
            return f"Error sending email: {str(e)}"
